name: deploy_frontend
# Deploys when push is made from the frontend folder
on:
  push:
    branches:
      - main
    paths:
      - 'Static Website/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name bhuegeleteststorage --auth-mode key -d '$web' -s 'Static Website/frontend/'
        #az storage blob upload-batch --account-name skelingtonboistorage --auth-mode key -d '$web' -s 'Static Website/frontend/'
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --resource-group "Static_Site" --profile-name "cdn-bhuegele-profile-1" --name "cdn-bhuegele-endpoint-1"
        #az cdn endpoint purge --content-paths "/*" --resource-group "Static_Site" --profile-name "cdn-skelingtonboi-profile" --name "cdn-skelingtonboi-endpoint"
  # Azure logout
      - name: logout
        run: |
            az logout
        if: always()